site_name: SU Tutor App
theme:
  name: material
  features:
    - navigation.instant
  # Light mode
  palette:
    - deep orange: "(prefers-color-scheme: light)"
      scheme: default
      primary: amber
      accent: amber
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      accent: amber
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Home: index.md
  - About: about.md
  - User Guide:
    - Getting Started: user/getting-started.md
    - Reporting: user/reporting.md
  - Developer Guide:
    - Getting Started: developers/getting-started.md
    - Backend:
      - Introduction: developers/backend/introduction.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition

site_url: https://southwestern-higher-learning.github.io/